### ISSUE TITLE
Apparent problem with file permissions on entrypoint.sh

### ISSUE THREAD

**Issue by oppodeldoc** [heygrady/docker-wordpress-starterkit#2]
@heygrady thanks so much for this awesome kit!

I ran into an issue on the first install of this using your most recent TLDR; instructions. when running them exactly as stated, the script was throwing an error on the `npm run docker:up:daemon` command:

```
$ npm run docker:up:daemon

docker-wordpress-starterkit@0.0.0 docker:up:daemon /Users/xxxxxx/tldr
npm run docker:up -- -d


docker-wordpress-starterkit@0.0.0 docker:up /Users/xxxxxx/tldr
npm run docker:pf -s && docker-compose up "-d"

Creating volume "tldr_data" with default driver
Creating tldr_db_1
Creating tldr_wordpress_1
ERROR: Container command '/entrypoint.sh' could not be invoked.
```

I found a few issues related to this on other projects, they suggested that the problem was that after copying entrypoint.sh, it needs to be set as an executable. The fix I added as part of this pull request  #1

One thing that is extremely confusing to me is that even when I fixed this, stopped all the containers and even restarted the default docker machine, I got the same error, even on a clean repo of this project. I was able to fix by completely deleting the default docker machine and starting from there. 

Seems like the incorrect permissions persisted across boots. Would re-provisioning fix this?

**Comment by heygrady** [comment]
Usually `docker-compose build` will fix that issue. Docker aggressively caches images so you have to tell it when it should rebuild after you've made changes to a Dockerfile or entry point. I added a command for that.

```
$ npm run docker:build
```

**Comment by heygrady** [comment]
Closing after merging the submitted pull request
