### ISSUE TITLE
Changing directory name from tldr breaks DB dump stuff

### ISSUE THREAD

**Issue by oppodeldoc** [heygrady/docker-wordpress-starterkit#3]
@heygrady You probably already know this but it's worth filing a todo on it. [This line](https://github.com/heygrady/docker-wordpress-starterkit/blob/master/package.json#L22) references the container `tldr_db_1` directly, so when the name tldr isn't used then this reference is empty:

`$(docker ps --format \"{{.ID}}\" --filter \"name=tldr_db_1\")`

Docker thinks you're looking for a container named 'mysqldump' at that point, so it errors out. Like I said, sure this is just a todo or feature request. I can expand on that if needed, but basically we should eventually be able to set a specific project name (slug or domain of the site) and use that to run these commands.

**Comment by heygrady** [comment]
Closing for now. There doesn't seem to be a standard way to obtain the "project name" that docker-compose uses. The following command generates what docker-compose uses when you don't provide a `COMPOSE_PROJECT_NAME` environment variable.

https://github.com/docker/compose/issues/2294

```
$(basename $(pwd) | sed -e 's/[^a-z0-9]//g')
```
