### ISSUE TITLE
Would be great to access MySQL instance via a GUI like Sequel Pro

### ISSUE THREAD

**Issue by oppodeldoc** [heygrady/docker-wordpress-starterkit#5]
Looking into this a bit, will submit pull request soon-ish...

**Comment by oppodeldoc** [comment]
Oh _snap_

Thanks to @heygrady doing some great groundwork here, this was a cinch. Just opened up the port in the docker-compose file and was able to access 3306 at localhost. I also found a great script that will automatically open up Sequel Pro to your Docker DB instance, and added that to one of the shortcuts, you can now open up the DB with `npm run docker:db:open`. 

Also updated docs, will go ahead and close with merge of #6

**Comment by heygrady** [comment]
Awesome! Thanks for the shout out :)
